import json
import os

# Load history file
history_path = "history/mercury_results_history.json"
output_path = "outputs/narrative_report.json"

# Ensure output directory exists
os.makedirs("outputs", exist_ok=True)

# Read history
with open(history_path, "r", encoding="utf-8-sig") as f:
    history = json.load(f)

# Build narrative summary
summary = {
    "total_events": len(history),
    "wins": sum(1 for h in history if h.get("result") == "yes"),
    "losses": sum(1 for h in history if h.get("result") == "no"),
    "notes": "Narrative summary generated by Mercury"
}

# Save narrative
with open(output_path, "w", encoding="utf-8-sig") as f:
    json.dump(summary, f, indent=4)

print("Narrative report created")
