import json
import os

history_path = "history/mercury_results_history.json"
narrative_path = "outputs/narrative_report.json"
output_path = "outputs/strategy_report.json"

os.makedirs("outputs", exist_ok=True)

# Load history
with open(history_path, "r", encoding="utf-8-sig") as f:
    history = json.load(f)

# Load narrative
with open(narrative_path, "r", encoding="utf-8-sig") as f:
    narrative = json.load(f)

# Compute basic metrics
roi = 0.0
wins = narrative["wins"]
losses = narrative["losses"]
total = narrative["total_events"]

if total > 0:
    roi = (wins - losses) / total

report = {
    "roi": roi,
    "wins": wins,
    "losses": losses,
    "total_events": total,
    "notes": "Strategy evaluation generated by Mercury"
}

with open(output_path, "w", encoding="utf-8-sig") as f:
    json.dump(report, f, indent=4)

print("Strategy report created")
